[package]
name = "vanilla-tweaks"
version = "1.6.0"
edition = "2021"
authors = ["burneddi <burneddi@protonmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.8", features = ["derive"] }
